const mongoose = require("mongoose");
const Caption = require("./models/captionModel");
const { mongoUrl } = require("./keys");

const captions = [
  { text: "🍃Nature is the art of God.", keyword: "nature" },
  { text: "🌄Serenity in every shade of green.", keyword: "nature" },
  { text: "🌲🌐Wandering where the Wi-Fi is weak.", keyword: "nature" },
  { text: "🍃🗺️A glimpse of paradise.", keyword: "nature" },
  { text: "🌄Sunset vibes and nature's hues.", keyword: "nature" },
  { text: "🌼 🗺️Chasing the golden hour.", keyword: "nature" },
  { text: "🎨Every picture tells a story.", keyword: "nature" },
  { text: "🌼 🌐Life's better in flip-flops.", keyword: "nature" },
  { text: "🍃Into the wild we go.", keyword: "nature" },
  { text: "🌲Let the mountains sing.", keyword: "nature" },
  { text: "Let the beauty of nature heal your soul.", keyword: "nature" },
  { text: "🌄🎨Nature is where the magic happens.", keyword: "nature" },
  { text: "🌼 Nature is the ultimate mood booster.", keyword: "nature" },
  { text: "🍃🌊Lost in the beauty of nature.", keyword: "nature" },
  { text: "🌼🗺️ In love with the great outdoors.", keyword: "nature" },
  { text: "🍃A walk in nature is a walk in peace.", keyword: "nature" },
  { text: "🌊This is heaven on Earth.", keyword: "nature" },
  { text: "🌲🌿 Simplicity in nature's beauty ", keyword: "nature" },
  { text: "🌿 🎨Colours are the smiles of nature.", keyword: "nature" },
  { text: "🍃🗺️The beauty of nature is all around us, we just need to take the time to appreciate it.", keyword: "nature" },
  { text: "🌊Life's a beach.", keyword: "nature" },
  { text: "🌊Beauty in abundance.", keyword: "nature" },
  { text: "🌿 My hearts long for soil on my feet and sun on my face.", keyword: "nature" },
  { text: "🍃🌿 Caught in the current of good vibes! ", keyword: "nature" },
  { text: "Sunkissed.", keyword: "nature" },
  { text: "🌼 🌿 Lost in the dreamy world of aesthetic nature.", keyword: "nature" },
  { text: "🌿 🎨Finding poetry in the landscape. ", keyword: "nature" },
  { text: "🌊Falling in love with every scenic view I see! ", keyword: "nature" },
  { text: "🍃🌿 Chill mode: activated.", keyword: "nature" },
  { text: "🌄Pause and enjoy the flow of life.", keyword: "nature" },
  { text: "🌿 Be like a tree: stand tall, grow deep roots, and reach for the sky", keyword: "nature" },
  { text: "🌼🌊 Paradise.", keyword: "nature" },
  { text: "🌿 Listen and delight in the soulful sounds of nature.", keyword: "nature" },
  { text: "🌄The best view comes after the hardest climb.", keyword: "nature" },
  { text: "🌲🌊Dancing with the waves and chasing sunsets.", keyword: "nature" },
  { text: "🌿🗺️ Standing in awe of nature's masterpiece.", keyword: "nature" },
  { text: "🌄Journey with an open heart. ", keyword: "nature" },
  { text: "🌊Living in the edge and loving every minute of it.", keyword: "nature" },
  { text: "Slow down to the pace of nature.", keyword: "nature" },
  { text: "🍃Nature is my medicine.", keyword: "nature" },
  { text: "🌼🗺️ In love with the world around me. ", keyword: "nature" },
  { text: "🌄Fresh air and good vibes!", keyword: "nature" },
  { text: "Let your heart wander in the wild and find its roots.", keyword: "nature" },
  { text: "🍃Taking a break from reality to chill in the great outdoors.", keyword: "nature" },
  { text: "🌼 A day in nature is a day well spent ", keyword: "nature" },
  { text: "🌊🌿 Nature heals the heart. ", keyword: "nature" },
  { text: "🌿 Catching the world's beauty through my lens! ", keyword: "nature" },
  { text: "🌄🗺️Turning nature's moments into timeless photos. ", keyword: "nature" },
  { text: "🌊A quiet moment in nature's company. ", keyword: "nature" },
  { text: "🌄🌿 Tree-mendously happy in nature's embrace. ", keyword: "nature" },

  { text: "Planting Dreams.", keyword: "plants" },
  { text: "Plant Happiness.", keyword: "plants" },
  { text: "The best magic comes in pots.", keyword: "plants" },
  { text: "Bloom where you are planted.", keyword: "plants" },
  { text: "Plant smiles, grow laughter.", keyword: "plants" },
  { text: "Life is better with plants.", keyword: "plants" },
  { text: "Plant dreams, pull weeds, and grow a happy life.", keyword: "plants" },
  { text: "Green vibes only.", keyword: "plants" },
  { text: "I'm having a plant-tastic day!", keyword: "plants" },
  { text: "Planting seeds of love.", keyword: "plants" },
  { text: "Plants = Pure happiness.", keyword: "plants" },
  { text: "Green companions, bringing life to my home.", keyword: "plants" },
  { text: "Houseplants: My natural stress relievers.", keyword: "plants" },
  { text: "Embracing the serenity of indoor greenery.", keyword: "plants" },
  { text: "The best therapy is plant therapy.", keyword: "plants" },
  { text: "My plant collection keeps growing, just like my passion for gardening.", keyword: "plants" },
  { text: "Plants make everything better.", keyword: "plants" },
  { text: "A little greenery can do wonders for the soul.", keyword: "plants" },
  { text: "Sprouting joy with every leaf.", keyword: "plants" },
  { text: "Nature's first-borns, teaching us patience and growth.", keyword: "plants" },
  { text: "Grow and glow.", keyword: "plants" },
  { text: "Find beauty in the botanical.", keyword: "plants" },
  { text: "Can't be-leaf how amazing plants are.", keyword: "plants" },
  { text: "Just like plants, we grow.", keyword: "plants" },
  { text: "Time spent among plants is never wasted time.", keyword: "plants" },
  { text: "In the garden of life, friends are the flowers that make it bloom.", keyword: "plants" },


  { text: "Finding peace in the rush of the falls.", keyword: "waterfalls" },
  { text: "Lost in the magic of falling water.", keyword: "waterfalls" },
  { text: "Falling in love with this place.", keyword: "waterfalls" },
  { text: "Nature's shower.", keyword: "waterfalls" },
  { text: "Finding paradise in every drop.", keyword: "waterfalls" },
  { text: "Lost in the sound of the waterfall.", keyword: "waterfalls" },
  { text: "Power.", keyword: "waterfalls" },
  { text: "Bliss.", keyword: "waterfalls" },
  { text: "Nature's wonder.", keyword: "waterfalls" },
  { text: "Waterfall magic.", keyword: "waterfalls" },
  { text: "Find your peace where the water falls.", keyword: "waterfalls" },
  { text: "Let the beauty of the waterfall inspire you.", keyword: "waterfalls" },
  { text: "There's no better place to find yourself than sitting by a waterfall and listening to its music.", keyword: "waterfalls" },
  { text: "Exploring hidden waterfalls.", keyword: "waterfalls" },
  { text: "Travel, explore, and chase waterfalls.", keyword: "waterfalls" },
  { text: "Adventure awaits at every waterfall.", keyword: "waterfalls" },
  { text: "Go with the flow.", keyword: "waterfalls" },
  { text: "Life is like a waterfall - always moving, always changing.", keyword: "waterfalls" },
  { text: "Eternal beauty.", keyword: "waterfalls" },
  { text: "Simply stunning.", keyword: "waterfalls" },
  { text: "Flow on and stay strong.", keyword: "waterfalls" },
  { text: "Nature's art.", keyword: "waterfalls" },
  { text: "Let your dreams cascade.", keyword: "waterfalls" },
  { text: "Our love is as endless as this waterfall.", keyword: "waterfalls" },
  { text: "Together, we create a cascade of memories.", keyword: "waterfalls" },
 
  { text: "Nothing but blue skies and ocean tides. 🌊💙", keyword: "ocean" },
  { text: "Saltwater soul, ocean heart. 🌊💙", keyword: "ocean" },
  { text: "Take me to the ocean and beyond. 🌊✨", keyword: "ocean" },
  { text: "Leave only footprints, take only memories. 👣📷", keyword: "ocean" },
  { text: "Sailing into golden horizons. ⛵🌅", keyword: "ocean" },
  { text: "Let the ocean be your guide. 🌊🗺️", keyword: "ocean" },
  { text: "The ocean is my endless muse. 🌊🎨", keyword: "ocean" },
  { text: "Let the rhythm of the ocean soothe your soul. 🌊🎵", keyword: "ocean" },
  { text: "Finding solace in the rhythm of the waves. 🌊🌀", keyword: "ocean" },
  { text: "Embrace the waves and find your flow. 🌊🌀”", keyword: "ocean" },
  { text: "Lost in the waves, found in the ocean 🌊🌅✨",keyword: "ocean" },
  { text: "Salty air, sandy hair, and endless vibes 🌊🍃🌞",keyword: "ocean" },
  { text: "Let the sea set you free 🌊🕊️💙",keyword: "ocean" },
  { text: "Happiness comes in waves 🌊😄☀️",keyword: "ocean" },
  { text: "Ocean vibes and good tides 🌊🌴✨",keyword: "ocean" },
  { text: "The ocean is my therapy 🌊🧘‍♀️💭",keyword: "ocean" },
  { text: "Waves are the universe's way of dancing 🌊💃🌟",keyword: "ocean" },
  { text: "Sea more, worry less 🌊💙🌅",keyword: "ocean" },
  { text: "Ocean child, wild and free 🌊✨🌿",keyword: "ocean" },
  { text: "Take me where the waves kiss the shore 🌊🏝️💕",keyword: "ocean" },
  { text: "Collecting seashells and memories 🌊🐚📸",keyword: "ocean" },
  { text: "In a sea of people, my soul craves the ocean 🌊✨🌏",keyword: "ocean" },
  { text: "Let the waves cleanse your soul 🌊🕊️✨",keyword: "ocean" },
  { text: "Born to chase the tides 🌊🌞🌈",keyword: "ocean" },
  { text: "The ocean is calling, and I must go 🌊📞✨",keyword: "ocean" },

  { text: "Sunsets over the sea, the perfect harmony. 🌅🌊", keyword: "sea" },
  { text: "Sea therapy for the soul. 🌊💆‍♀️", keyword: "sea" },
  { text: "Finding my inner peace by the sea. 🌊🧘‍♀️", keyword: "sea" },
  { text: "Seascape serenity. 🌊🌅", keyword: "sea" },
  { text: "Let the sea set you free. 🌊✨", keyword: "sea" },
  { text: "Lost in paradise. 🏝️💫", keyword: "sea" },
  { text: "Catch the wave of happiness. 🌊😃", keyword: "sea" },
  { text: "Lost in the sea of dreams. 💭🌊", keyword: "sea" },
  { text: "Sunshine and seashells. ☀️🐚", keyword: "sea" },
  { text: "Sea you soon! 🌊😉", keyword: "sea" },
  { text: "Life is better when you're by the sea. 🌊💙", keyword: "sea" },
  { text: "Dive into the magic of the sea. 🌊✨", keyword: "sea" },
  { text: "Sun, sea, and inner peace.☀️🌊💙", keyword: "sea" },
  { text: "Driftwood dreams and ocean streams.⛵🌊", keyword: "sea" },
  { text: "Serenity found in every wave.🌊💦", keyword: "sea" },
  { text: "The cure for anything is salt water: sweat, tears or the sea.🌅🌴🌬️", keyword: "sea" },
  { text: "The sound and smell of the sea cleanses my soul.🌊💙", keyword: "sea" },
  { text: "We dream in colors borrowed from the sea.🌅🌊", keyword: "sea" },
  { text: "Friends, sun, sand and sea. That sounds like a summer to me.🌊😉", keyword: "sea" },
  { text: "Life is better with a splash of saltwater. 🌊💦", keyword: "sea" },
  { text: "Surf, sun, and good vibes. 🏄☀️✌️", keyword: "sea" },
  { text: "Sunsets, palm trees, and a sea breeze. 🌅🌴🌬️", keyword: "sea" },
  { text: "Sail away into the horizon. ⛵🌅", keyword: "sea" },
  { text: "Sailing through life, one wave at a time. ⛵🌊", keyword: "sea" },
  { text: "Tide and time wait for no man. 🌊⌛", keyword: "sea" },
  { text: "In need of vitamin sea. 🌊🌞", keyword: "sea" },

  { text: "Life's a wave, catch it! 🌊🏄", keyword: "beach" },
  { text: "Beach life is the best life. 🏖️🌅", keyword: "beach" },
  { text: "Sandy beaches and palm trees. 🏖️🌴", keyword: "beach" },
  { text: "Just another day in paradise. 🏝️😊", keyword: "beach" },
  { text: "Life is better with a little sand between your toes and saltwater in your hair. 🏖️🌊", keyword: "beach" },
  { text: "Beach therapy is the best therapy. 🏖️💆‍♀️", keyword: "beach" },
  { text: "Life's a beach, ride the waves. 🌊🏄", keyword: "beach" },
  { text: "Seashells and sunshine. 🐚☀️", keyword: "beach" },
  { text: "Sunsets and palm trees. 🌅🌴", keyword: "beach" },
  { text: "Dreaming of endless summers. 🌞🌊", keyword: "beach" },
  { text: "Life's a beach, and I'm just playing in the sand.", keyword: "beach" },
  { text: "Mermaid vibes only.", keyword: "beach" },
  { text: "My happy place.", keyword: "beach" },
  { text: "I followed my heart, and it led me to the beach.", keyword: "beach" },
  { text: "Sandy toes, sun-kissed nose!", keyword: "beach" },
  { text: "Leave only footprints, take only memories. 👣📷", keyword: "beach" },
  { text: "Catch the wave of happiness. 🌊😃", keyword: "beach" },
  { text: "Sunsets and palm trees make the perfect company. 🌅🌴", keyword: "beach" },
  { text: "The best memories are made in flip-flops.", keyword: "beach" },
  { text: "Vacation mode: activated.", keyword: "beach" },
  { text: "Salt water heals everything.", keyword: "beach" },
  { text: "Summer mode: Activated.", keyword: "beach" },
  { text: "B.E.A.C.H.: Best Escape Anyone Can Have.", keyword: "beach" },
  { text: "Current mood: 🏖 🌊☀️👙😎", keyword: "beach" },
  { text: "Good times and tan lines.", keyword: "beach" },

  { text: "Coffee, books, and rain.", keyword: "rain" },
  { text: "Drips and dreams on this rainy day 💧✨", keyword: "rain" },
  { text: "When the sky cries, I smile 🌧️😊", keyword: "rain" },
  { text: "My happy place is under the clouds 🌧️😄", keyword: "rain" },
  { text: "Drizzle dazzle 💦✨", keyword: "rain" },
  { text: "Nature's glitter 💧🌟", keyword: "rain" },
  { text: "Chill ❄️", keyword: "rain" },
  { text: "Moody skies, creative mind 🌧️🎨", keyword: "rain" },
  { text: "Crystal tears from the heavens 💎😢", keyword: "rain" },
  { text: "Rain's own choreography ☔💫", keyword: "rain" },

  { text: "✨ Glow from the inside, sparkle on the outside.", keyword: "beauty" },
  { text: "💖 Beauty is about being comfortable in your own skin.", keyword: "beauty" },
  { text: "🌈 Embrace every shade of you.", keyword: "beauty" },
  { text: "🌺 Beneath the makeup and behind the smile, I'm just a girl.", keyword: "beauty" },
  { text: "🌟 Flaunting flaws and all.", keyword: "beauty" },
  { text: "❤️ Beauty isn't about looks, it's about feeling good.", keyword: "beauty" },
  { text: "👁️ Eyes speak the loudest, make them pop!", keyword: "beauty" },
  { text: "🖤 A little mascara, a lot of confidence.", keyword: "beauty" },
  { text: "🎨 Makeup: Painting the face canvas.", keyword: "beauty" },
  { text: "💋 Lips, lashes, and a whole lot of sass.", keyword: "beauty" },
  { text: "Keep smiling and let your 😘 shine", keyword: "beauty" },
  { text: "Love. Laugh. Live. 😊", keyword: "beauty" },
  { text: "Forever young at heart. 💖", keyword: "beauty" },
  { text: "Too glam to give a damn. 💅✨", keyword: "beauty" },
  { text: "Smile and slay the day! 😊🔥", keyword: "beauty" },
  { text: "Just wing it. Eyeliner, life, everything. ✨😉", keyword: "beauty" },
  { text: "Just a girl with a dream and a super cute outfit. 💭👗", keyword: "beauty" },
  { text: "Classy is the original black. 🖤", keyword: "beauty" },
  { text: "When in doubt, add more glitter. ✨✨✨", keyword: "beauty" },
  { text: "Leave a little sparkle wherever you go. ✨✨✨", keyword: "beauty" },
  { text: "Make them stop and stare. 👀🔥", keyword: "beauty" },
  { text: "Sweeter than honey. 🍯🍯🍯", keyword: "beauty" },
  { text: "Every day is a fashion show, and the world is your runway. 🌍👗", keyword: "beauty" },
  { text: "Follow your heart and trust the journey. 💞🌈", keyword: "beauty" },
  { text: "Life is short, make every hair flip count. 💁‍♀️💃", keyword: "beauty" },

  { text: "📸 Capturing life one click at a time.", keyword: "photography" },
  { text: "✨ Through the lens, I find magic.", keyword: "photography" },
  { text: "🌍 Lost in the world that isn't mine.", keyword: "photography" },
  { text: "❄️ Moments seized, memories frozen.", keyword: "photography" },
  { text: "🖼 Every shot tells a tale.", keyword: "photography" },
  { text: "🌓 Painting with light and shadows.", keyword: "photography" },
  { text: "🗣️ When words fail, photos speak.", keyword: "photography" },
  { text: "🌅 Chasing sunsets and dreams.", keyword: "photography" },
  { text: "💖 There's beauty in every perspective.", keyword: "photography" },
  { text: "🖼️ Frame by frame, making memories.", keyword: "photography" },

  { text: "🤳 Just me, myself, and my selfie.", keyword: "selfie" },
  { text: "🔄 Because every angle matters.", keyword: "selfie" },
  { text: "🎨 Life's a filter. Choose yours wisely.", keyword: "selfie" },
  { text: "🪐 In my own little universe.", keyword: "selfie" },
  { text: "🔮 Reflecting on the reflections.", keyword: "selfie" },
  { text: "😎 Serving looks, not tea!", keyword: "selfie" },
  { text: "📱 A selfie a day keeps the blues away.", keyword: "selfie" },
  { text: "💡 Caught in my best light.", keyword: "selfie" },
  { text: "👀 Eyes on the prize, selfie surprise!", keyword: "selfie" },
  { text: "📸 Flipping the camera, flipping the narrative.", keyword: "selfie" },

  { text: "🎥 Rolling into your feed like 🌀.", keyword: "reels" },
  { text: "📖 Short story, big impact!", keyword: "reels" },
  { text: "🎞️ From my reel life to your real life.", keyword: "reels" },
  { text: "⌛ Got a minute? Let's spin a tale.", keyword: "reels" },
  { text: "📼 Reel dreams in digital streams.", keyword: "reels" },
  { text: "🌌 Where reality meets reel fantasy.", keyword: "reels" },
  { text: "🔄 Let's put life on a loop.", keyword: "reels" },
  { text: "🎥 Catching moments, one reel at a time.", keyword: "reels" },
  { text: "⏳ Making moments count… in 60 seconds.", keyword: "reels" },
  { text: "🎵 Turn up the volume, let's dance through life!", keyword: "reels" },

  { text: "✨ Inspiring one post at a time.", keyword: "influencer" },
  { text: "🌟 Your daily dose of motivation and sparkle.", keyword: "influencer" },
  { text: "💭 Turned my dreams into my day job.", keyword: "influencer" },
  { text: "❤️ Leading with heart, influencing with purpose.", keyword: "influencer" },
  { text: "🤝 Together, we make magic.", keyword: "influencer" },
  { text: "💡 Bringing light, love, and a little inspo.", keyword: "influencer" },
  { text: "🔥 Chasing passions, not just followers.", keyword: "influencer" },
  { text: "💯 In the business of being real.", keyword: "influencer" },
  { text: "🎖️ More than an influencer - a game changer.", keyword: "influencer" },
  { text: "❤️ Every click, every like, every heart: for you.", keyword: "influencer" },

  { text: "👠 Strutting my stuff, one outfit at a time.", keyword: "fashion" },
  { text: "✈️ Dress like you're going places.", keyword: "fashion" },
  { text: "🕰 Fashion fades, style is eternal.", keyword: "fashion" },
  { text: "✨ Stitched together with dreams and sequins.", keyword: "fashion" },
  { text: "🌟 In a world full of trends, I want to be a classic.", keyword: "fashion" },
  { text: "💁‍♀️ Wear it with confidence, it's the best accessory.", keyword: "fashion" },
  { text: "👗 Every day's a runway.", keyword: "fashion" },
  { text: "🔥 Turn heads, break norms.", keyword: "fashion" },
  { text: "🧵 Fabric fantasies and style stories.", keyword: "fashion" },
  { text: "👩‍🦰 Clothes aren't going to change the world. The women who wear them will.", keyword: "fashion" },

  { text: "🌍 Wanderlust: It's more than a passion, it's a lifestyle.", keyword: "travel" },
  { text: "🧭 Lost in the right direction.", keyword: "travel" },
  { text: "📸 Collecting moments, not things.", keyword: "travel" },
  { text: "🛂 Another stamp on the passport, another story to tell.", keyword: "travel" },
  { text: "🌄 See the world, one adventure at a time.", keyword: "travel" },
  { text: "❤️ Wherever I go, I leave a piece of my heart.", keyword: "travel" },
  { text: "🗺️ Journeying through the atlas of life.", keyword: "travel" },
  { text: "🏖️ Sun, sand, and spontaneous trips.", keyword: "travel" },
  { text: "📚 The world is a book, and every trip is a new page.", keyword: "travel" },
  { text: "✈️ Chasing horizons 🌅 and collecting memories 🌍", keyword: "travel" },

  { text: "🏡 Where every guest feels like home.", keyword: "hospitality" },
  { text: "🛌 Experience luxury, comfort, and warmth, all under one roof.", keyword: "hospitality" },
  { text: "🌟 More than a stay, it's an experience.", keyword: "hospitality" },
  { text: "❤️ Crafting memorable moments for every guest.", keyword: "hospitality" },
  { text: "🛏️ Your comfort is our mission.", keyword: "hospitality" },
  { text: "🤗 From our family to yours, welcome home.", keyword: "hospitality" },
  { text: "🌆 A haven of hospitality.", keyword: "hospitality" },
  { text: "🔐 Check-in to serenity, check out with memories.", keyword: "hospitality" },
  { text: "💭 We're in the business of making memories.", keyword: "hospitality" },
  { text: "🧸 Where every detail speaks of care and comfort.", keyword: "hospitality" },

  { text: "🍴 Taste buds on a flavor journey.", keyword: "food" },
  { text: "🍰 Life's too short for average food.", keyword: "food" },
  { text: "❤️ Food is my love language.", keyword: "food" },
  { text: "🍛 Edible art, one plate at a time.", keyword: "food" },
  { text: "🌍 Eat well, travel often.", keyword: "food" },
  { text: "😋 In the mood for some food.", keyword: "food" },
  { text: "🍔 Bite into happiness.", keyword: "food" },
  { text: "❤️ Where flavor and love collide.", keyword: "food" },
  { text: "🌮 Eating my way around the world.", keyword: "food" },
  { text: "🥘 Plateful of passion and perfection.", keyword: "food" },

  { text: "🥤 Sipping on sunshine.", keyword: "beverage" },
  { text: "☕ Life's brew-tiful with a drink in hand.", keyword: "beverage" },
  { text: "🍷 Pour decisions lead to the best memories.", keyword: "beverage" },
  { text: "🍹 A symphony in every sip.", keyword: "beverage" },
  { text: "🥂 Lifting spirits, one drink at a time.", keyword: "beverage" },
  { text: "📖 Where every sip tells a story.", keyword: "beverage" },
  { text: "🍻 Raising a toast to the moments that matter.", keyword: "beverage" },
  { text: "☕ From the bean to the cup, it's all about passion.", keyword: "beverage" },
  { text: "🍺 Brewed to perfection, served with love.", keyword: "beverage" },
  { text: "💧 Hydrate with style and substance.", keyword: "beverage" },

  { text: "🍳 Cooking up storms and stories.", keyword: "cooking" },
  { text: "✨ Where magic meets the kitchen.", keyword: "cooking" },
  { text: "🥣 Stirring passion into every dish.", keyword: "cooking" },
  { text: "🔄 Cook, eat, love, repeat.", keyword: "cooking" },
  { text: "📖 Behind every dish is a tale of tradition.", keyword: "cooking" },
  { text: "❤️ Bringing love to the table, one recipe at a time.", keyword: "cooking" },
  { text: "🍴 Life's a kitchen; whip up something special.", keyword: "cooking" },
  { text: "🥘 Every flavor has a story.", keyword: "cooking" },
  { text: "🔬 The kitchen: where science meets art.", keyword: "cooking" },
  { text: "🍲 Cooking is love made edible.", keyword: "cooking" },

  { text: "🌱 Plant power in every bite.", keyword: "veggie" },
  { text: "🥦 Veggie vibes only.", keyword: "veggie" },
  { text: "🌎🍏 Vegan: because compassion tastes amazing.", keyword: "veggie" },
  { text: "❤️ For the love of greens and the planet.", keyword: "veggie" },
  { text: "🥗 Nourishing the soul, one plant-based meal at a time.", keyword: "veggie" },
  { text: "🥬 Kale yeah, I'm vegan!", keyword: "veggie" },
  { text: "💚 Eating kindly, living kindly.", keyword: "veggie" },
  { text: "🌿 Fueled by plants and positivity.", keyword: "veggie" },
  { text: "🌈 Taste the rainbow, eat your veggies.", keyword: "veggie" },
  { text: "🌍 Mother Earth's best recipes.", keyword: "veggie" },

  { text: "💦 Sweat, smile, repeat.", keyword: "fitness" },
  { text: "🏋️ Fitness: not a destination but a way of life.", keyword: "fitness" },
  { text: "💥 Pushing limits, breaking barriers.", keyword: "fitness" },
  { text: "💪 Strong mind, stronger body.", keyword: "fitness" },
  { text: "🔥 Every workout counts.", keyword: "fitness" },
  { text: "🪞 Making peace with the mirror, one rep at a time.", keyword: "fitness" },
  { text: "🔋 Fueling my fire, chasing my goals.", keyword: "fitness" },
  { text: "🚫 Dedication doesn't have an off day.", keyword: "fitness" },
  { text: "📈 Chase progress, not perfection.", keyword: "fitness" },
  { text: "🚴 Train hard, live easy.", keyword: "fitness" },

  { text: "⚽ Passion in play, heart in every game.", keyword: "sports" },
  { text: "🏀 More than a game, it's a way of life.", keyword: "sports" },
  { text: "🥇 Champion mindset, every single day.", keyword: "sports" },
  { text: "🏆 Winning hearts, one game at a time.", keyword: "sports" },
  { text: "💦 Sweat and sacrifice, that's the secret.", keyword: "sports" },
  { text: "🎖 In the zone and on the throne.", keyword: "sports" },
  { text: "⛹️‍♂️ Play hard, dream big.", keyword: "sports" },
  { text: "🏁 Victory is in the journey, not just the destination.", keyword: "sports" },
  { text: "💡 Where there's a will, there's a play.", keyword: "sports" },
  { text: "💪 Leave it all on the field.", keyword: "sports" },

  { text: "🎮 Eat, sleep, game, repeat.", keyword: "games" },
  { text: "🌌 Pixelated dreams, real passion.", keyword: "games" },
  { text: "🕹 In the game of life, I choose to play.", keyword: "games" },
  { text: "⬆️ Level up in the virtual world and reality.", keyword: "games" },
  { text: "🔄 Respawn, reload, reign!", keyword: "games" },
  { text: "🎲 Gaming: where every adventure counts.", keyword: "games" },
  { text: "💡 Power on, game strong.", keyword: "games" },
  { text: "📺 Beyond the screen, into the story.", keyword: "games" },
  { text: "🏆 Unlocking achievements and potential.", keyword: "games" },
  { text: "⏰ One more game? Always.", keyword: "games" },

  { text: "🌦 It's okay not to be okay.", keyword: "mental health" },
  { text: "🌱 Healing one day at a time.", keyword: "mental health" },
  { text: "💡 Mental health matters, every day.", keyword: "mental health" },
  { text: "📖 Your story is valuable. Keep telling it.", keyword: "mental health" },
  { text: "💪 Find strength in vulnerability.", keyword: "mental health" },
  { text: "🌱 Grow through what you go through.", keyword: "mental health" },
  { text: "❤️ Self-care isn't selfish. It's necessary.", keyword: "mental health" },
  { text: "🌍 Every mind has its own journey.", keyword: "mental health" },
  { text: "🚧 Embrace the journey, even the bumps.", keyword: "mental health" },
  { text: "💖 Your feelings are valid, and so are you.", keyword: "mental health" },

  { text: "🚀 Dream big, hustle harder.", keyword: "motivation" },
  { text: "🎯 Chase goals, not dreams.", keyword: "motivation" },
  { text: "🔥 Let the passion burn brighter than your fears.", keyword: "motivation" },
  { text: "🧗 Every challenge is a stepping stone to greatness.", keyword: "motivation" },
  { text: "🌞 Wake up with purpose. Sleep with satisfaction.", keyword: "motivation" },
  { text: "🏔 The best view comes after the hardest climb.", keyword: "motivation" },
  { text: "💡 Let your ambition fuel your journey.", keyword: "motivation" },
  { text: "🌱 Growth begins at the end of your comfort zone.", keyword: "motivation" },
  { text: "🏆 Determined today, successful tomorrow.", keyword: "motivation" },
  { text: "💪 Turn your 'can'ts' into 'cans' and dreams into plans.", keyword: "motivation" },

  { text: "❤️ Falling in love with myself, one day at a time.", keyword: "self love" },
  { text: "🌈 Embrace every shade of you.", keyword: "self love" },
  { text: "🛤 Self-love isn't a destination; it's a journey.", keyword: "self love" },
  { text: "💪 I am enough, and so are you.", keyword: "self love" },
  { text: "🧖‍♀️ Me-time is the best time.", keyword: "self love" },
  { text: "🎉 Celebrate yourself, because you're worth it.", keyword: "self love" },
  { text: "❤️🥇 Love yourself first, and everything else falls in line.", keyword: "self love" },
  { text: "🎨 I am my own muse.", keyword: "self love" },
  { text: "🌺 Beauty begins the moment you decide to be yourself.", keyword: "self love" },
  { text: "💖 Choosing self-love over self-doubt.", keyword: "self love" },

  { text: "🌌 Finding peace within the chaos.", keyword: "relax" },
  { text: "🌬 Inhale positivity, exhale negativity.", keyword: "relax" },
  { text: "🌙 Stillness speaks volumes.", keyword: "relax" },
  { text: "🛤 Journey to the center of the soul.", keyword: "relax" },
  { text: "🧘‍♀️ Meditation: because some questions can't be answered by Google.", keyword: "relax" },
  { text: "🌊 Serenity now and always.", keyword: "relax" },
  { text: "🎧 Tune in to tune out.", keyword: "relax" },
  { text: "🌌 Embrace the silence, hear the universe.", keyword: "relax" },
  { text: "🌊 Floating on waves of tranquility.", keyword: "relax" },
  { text: "🕊 Every breath is a step closer to inner peace.", keyword: "relax" },

  { text: "🐾 Furry friends make the best companions.", keyword: "pet" },
  { text: "🐱🐶 Paws and reflect on life's little joys.", keyword: "pet" },
  { text: "🐹🐰 Whiskers, tails, and endless tales.", keyword: "pet" },
  { text: "🐈 Happiness is a warm lap and a soft purr.", keyword: "pet" },
  { text: "🐾 Life is better with fur.", keyword: "pet" },
  { text: "❤️ Who rescued who?", keyword: "pet" },
  { text: "🐶🐱 Every pet deserves a loving human.", keyword: "pet" },
  { text: "🐾🖼 Making memories, one paw print at a time.", keyword: "pet" },
  { text: "😺 Because every day is a good day with a pet.", keyword: "pet" },
  { text: "❤️ Love is a four-legged word.", keyword: "pet" },

  { text: "🐶 Life's better with a wagging tail.", keyword: "dog" },
  { text: "🎉 Every dog has its day, and today's mine!", keyword: "dog" },
  { text: "🌲 Barking our way into adventures.", keyword: "dog" },
  { text: "🐾 Paws, play, and endless cuddles.", keyword: "dog" },
  { text: "🐕 My fur-ever friend.", keyword: "dog" },
  { text: "😃 Happiness starts with a wet nose and ends with a tail.", keyword: "dog" },
  { text: "🌟 Keeping the 'wonder' in 'wonderful'.", keyword: "dog" },
  { text: "😂 In dog years, I'm always happy.", keyword: "dog" },
  { text: "❤️ Canine companion, lifetime of love.", keyword: "dog" },
  { text: "⏰ Who needs an alarm clock when you have a dog?", keyword: "dog" },

  { text: "🐾 Paws and reflect: life's purrfect with a cat.", keyword: "cat" },
  { text: "😻 Whisker-tales of feline charm.", keyword: "cat" },
  { text: "🎨 Every cat is a masterpiece painted with mischief and grace.", keyword: "cat" },
  { text: "👑 Claiming the throne, one purr at a time.", keyword: "cat" },
  { text: "🐱 When life gets tough, there's always cat cuddles.", keyword: "cat" },
  { text: "✨ Pouncing into your feed with a feline finesse.", keyword: "cat" },
  { text: "🌜 Midnight prowler, daytime napper.", keyword: "cat" },
  { text: "🎶 'Fur' real, my cat's the main note in my life's song.", keyword: "cat" },
  { text: "💕 Love is a four-legged furball purring beside you.", keyword: "cat" },
  { text: "🌌 Exploring galaxies, one kitty eyeblink at a time.", keyword: "cat" },

  { text: "🌞 Sun-kissed skin and endless blue skies.", keyword: "summer" },
  { text: "🍉 Sweet summer memories in the making.", keyword: "summer" },
  { text: "🌊 Waves crashing, spirits soaring.", keyword: "summer" },
  { text: "🍦 Melting moments under the golden sun.", keyword: "summer" },
  { text: "🌴 Living on island time all summer long.", keyword: "summer" },
  { text: "🏖️ Sandy toes, sunkissed nose.", keyword: "summer" },
  { text: "🌻 Blooming bright in the summer light.", keyword: "summer" },
  { text: "🚣 Making a splash in summer's embrace.", keyword: "summer" },
  { text: "🔥 Hot days, cool nights, summer delights.", keyword: "summer" },
  { text: "🍹 Sipping on sunshine and good vibes.", keyword: "summer" },

  { text: "🌸 Blossoming anew with spring's tender touch.", keyword: "spring" },
  { text: "🍃 Fresh starts and floral hearts.", keyword: "spring" },
  { text: "🦋 Fluttering through spring's gentle breeze.", keyword: "spring" },
  { text: "💧 Dancing in the rhythm of spring rain.", keyword: "spring" },
  { text: "🌷 Blooms, beauty, and boundless joy.", keyword: "spring" },
  { text: "🌼 Sunlit days and fresh bouquets.", keyword: "spring" },
  { text: "🌿 Green dreams and springtime themes.", keyword: "spring" },
  { text: "🐣 A season of rebirth and renewal.", keyword: "spring" },
  { text: "💕 Spring: nature's way of saying 'Let's Party!'.", keyword: "spring" },
  { text: "🎨 Painting my days with spring shades.", keyword: "spring" },

  { text: "🍂 Falling for autumn's golden embrace.", keyword: "autumn" },
  { text: "🎃 Spooky vibes and autumn skies.", keyword: "autumn" },
  { text: "🍁 Crunchy leaves, cozy sleeves.", keyword: "autumn" },
  { text: "🔥 Sweater weather and warm fires.", keyword: "autumn" },
  { text: "🌙 Harvest moon and an autumn tune.", keyword: "autumn" },
  { text: "🌲 Forest hues and autumn's muse.", keyword: "autumn" },
  { text: "☕ Warm drinks and cool autumn nights.", keyword: "autumn" },
  { text: "📖 Stories written in shades of amber and gold.", keyword: "autumn" },
  { text: "🍎 Apple picking and autumn picnicking.", keyword: "autumn" },
  { text: "🌰 Nurturing the soul with autumn's glow.", keyword: "autumn" },

  { text: "❄️ Winter's whisper and snowflake kisses.", keyword: "winter" },
  { text: "🌨️ Snow-covered dreams and frosty beams.", keyword: "winter" },
  { text: "⛄ Building memories, one snowman at a time.", keyword: "winter" },
  { text: "🔥 Warm hearts, cold nights.", keyword: "winter" },
  { text: "🍫 Hot cocoa, cozy throws, and winter glows.", keyword: "winter" },
  { text: "🏂 Sliding into winter wonderland adventures.", keyword: "winter" },
  { text: "🌌 Starry nights and sparkling lights.", keyword: "winter" },
  { text: "🎄 Tinsel tales and winter trails.", keyword: "winter" },
  { text: "🧤 Mitten moods and comfort foods.", keyword: "winter" },
  { text: "🛷 Sleighing the winter game!", keyword: "winter" },

  { text: "👫 Together is our favorite place to be.", keyword: "love" },
  { text: "💖 Every love story is beautiful, but ours is my favorite.", keyword: "love" },
  { text: "🏰 Building dreams and memories, hand in hand.", keyword: "love" },
  { text: "🌍 Us against the world.", keyword: "love" },
  { text: "❤️ Love's journey, best traveled together.", keyword: "love" },
  { text: "🌌 Finding adventures, one embrace at a time.", keyword: "love" },
  { text: "💞 Two souls, one heart.", keyword: "love" },
  { text: "😍 Lost in love and loving it.", keyword: "love" },
  { text: "✨ Every moment with you is like catching a star.", keyword: "love" },
  { text: "📖 Side by side, chapter by chapter.", keyword: "love" },
  { text: "💍 And so, the adventure begins.", keyword: "love" },
  { text: "🤵👰 Together is a beautiful place to be.", keyword: "love" },
  { text: "🥂 Love, laughter, and happily ever after.", keyword: "love" },
  { text: "👣 From this day forward, you shall not walk alone.", keyword: "love" },
  { text: "💋 Sealed with a kiss and a promise.", keyword: "love" },
  { text: "💃🕺 To love, honor, and dance the night away.", keyword: "love" },
  { text: "❤️ Tying the knot, and hearts together.", keyword: "love" },
  { text: "🌹 The start of forever and always.", keyword: "love" },
  { text: "🏰 Once in a while, in the middle of an ordinary life, love gifts us a fairytale.", keyword: "love" },
  { text: "🎉 With this ring, we begin everything.", keyword: "love" },

  { text: "🧙‍♀️ Witching you a spooktacular Halloween!", keyword: "halloween" },
  { text: "👻 Ghouls just wanna have fun.", keyword: "halloween" },
  { text: "🍷 Eat, drink, and be scary.", keyword: "halloween" },
  { text: "👀 Here for the boos!", keyword: "halloween" },
  { text: "🎃 Too cute to spook.", keyword: "halloween" },
  { text: "😈 Creep it real.", keyword: "halloween" },
  { text: "💄 If you've got it, haunt it.", keyword: "halloween" },
  { text: "🍂 Life is gourd when it's Halloween.", keyword: "halloween" },
  { text: "🍬 Ghostly greetings and spooky treats!", keyword: "halloween" },
  { text: "🦇 Feeling fang-tastic this Halloween night.", keyword: "halloween" },

  { text: "🌹 Love is in the air and it smells like roses.", keyword: "valentine" },
  { text: "💓 Every day with you feels like Valentine's Day.", keyword: "valentine" },
  { text: "🍫 All you need is love (and maybe some chocolate).", keyword: "valentine" },
  { text: "💓 My heart beats a little faster because of you.", keyword: "valentine" },
  { text: "🍬 Sweet moments and sweeter chocolates.", keyword: "valentine" },
  { text: "🏹 Cupid called, he says you've stolen my heart.", keyword: "valentine" },
  { text: "🌷 Roses are red, violets are blue, my Valentine's Day is perfect because of you.", keyword: "valentine" },
  { text: "✨ Love is the closest thing we have to magic.", keyword: "valentine" },
  { text: "🎁 Wrapped up in love and all its wonders.", keyword: "valentine" },
  { text: "❤️ Counting the ways I adore you, but always needing more.", keyword: "valentine" },

  { text: "🎉 New year, new beginnings, endless possibilities.", keyword: "new year" },
  { text: "📆 365 new days, 365 new chances.", keyword: "new year" },
  { text: "🥂 Cheers to the adventures yet to come!", keyword: "new year" },
  { text: "✨ New year, same dreams, fresh starts.", keyword: "new year" },
  { text: "📖 Page 1 of 36 Let the story begin.", keyword: "new year" },
  { text: "🎆 Embracing the magic that a new year brings.", keyword: "new year" },
  { text: "👋 Goodbye past, hello future!", keyword: "new year" },
  { text: "💫 New year's glow and a world to explore.", keyword: "new year" },
  { text: "🚀 New chapters, new adventures.", keyword: "new year" },
  { text: "📸 Here's to another year of making memories.", keyword: "new year" },

  { text: "🎂 Another year older, another year wiser.", keyword: "birthday" },
  { text: "🍰 Birthdays are nature's way of telling us to eat more cake!", keyword: "birthday" },
  { text: "🎈 Celebrating life and its sweet moments.", keyword: "birthday" },
  { text: "🧸 Growing old is mandatory, but growing up is optional.", keyword: "birthday" },
  { text: "👑 Here's to another year of fabulous me!", keyword: "birthday" },
  { text: "🍷 Aging like fine wine, getting better with time.", keyword: "birthday" },
  { text: "⏳ Making my years count, instead of counting the years.", keyword: "birthday" },
  { text: "🎉 Balloons, cake, and a sprinkle of mischief.", keyword: "birthday" },
  { text: "❤️ Forever young at heart.", keyword: "birthday" },
  { text: "🌟 It's not the years in your life, but the life in your years that counts.", keyword: "birthday" },

  { text: "🐇 Hoppin' into Easter with joy!", keyword: "easter" },
  { text: "🥚 Eggs-tra special memories being made today.", keyword: "easter" },
  { text: "🐣 Easter: The only time it's okay to put all your eggs in one basket!", keyword: "easter" },
  { text: "🐰 Every bunny needs some bunny to love.", keyword: "easter" },
  { text: "🌼 Celebrating life, love, and the promise of new beginnings.", keyword: "easter" },
  { text: "🌸 Spring blossoms and Easter blessings.", keyword: "easter" },
  { text: "🍫 Rolling into the festive spirit.", keyword: "easter" },
  { text: "🧺 Baskets full of joy and chocolate!", keyword: "easter" },
  { text: "🎶 Here comes Peter Cottontail, hopping down the bunny trail.", keyword: "easter" },
  { text: "✨ Easter spells out a beautiful renewal of spirit.", keyword: "easter" },

  { text: "🔔 Jingle all the way and make spirits bright.", keyword: "christmas" },
  { text: "🎁 Wrapped up in the holiday spirit.", keyword: "christmas" },
  { text: "❄️ Christmas isn't a season, it's a feeling.", keyword: "christmas" },
  { text: "🧥 Sweaters, snowflakes, and heartwarming tales.", keyword: "christmas" },
  { text: "🎄 Decking the halls and spreading cheer.", keyword: "christmas" },
  { text: "🍪 All I want for Christmas is you (and maybe some cookies).", keyword: "christmas" },
  { text: "🎅 Santa's favorite on the nice list!", keyword: "christmas" },
  { text: "🌟 It's the most wonderful time of the year!", keyword: "christmas" },
  { text: "💋 Under the mistletoe magic.", keyword: "christmas" },
  { text: "🎇 May your days be merry and bright.", keyword: "christmas" },

  { text: "🙏 Giving thanks for the simple joys in life.", keyword: "thanking" },
  { text: "🥧 Pies before guys, always.", keyword: "thanking" },
  { text: "❤️ Thankful, grateful, and blessed beyond measure.", keyword: "thanking" },
  { text: "🍗 Stuffed with food and filled with gratitude.", keyword: "thanking" },
  { text: "👪 Gathered at the table, bound by thankfulness.", keyword: "thanking" },
  { text: "🦃 Gobble till you wobble!", keyword: "thanking" },
  { text: "🌽 Count your blessings, not your calories.", keyword: "thanking" },
  { text: "🍂 Where there's Thanksgiving, there's food, friends, and family.", keyword: "thanking" },
  { text: "🍽️ Feast mode: On!", keyword: "thanking" },
  { text: "🌟 Life is better when you're grateful.", keyword: "thanking" },

  { text: "🎉 The countdown begins! Are you as excited as we are?", keyword: "event" },
  { text: "📅 Save the date, because you won't want to miss this!", keyword: "event" },
  { text: "Get ready for a night to remember! 🌌🎈", keyword: "event" },
  { text: "🎟️ Tickets are selling fast! Grab yours before the're gone.", keyword: "event" },
  { text: "The event of the year is just around the corner! 🥳 Are you in?", keyword: "event" },
  { text: "Ready for some magic? ✨ Join us this weekend.", keyword: "event" },
  { text: "Let's make memories together! 📸 RSVP now!", keyword: "event" },
  { text: "Brace yourselves, the excitement is about to go down! 🎊", keyword: "event" },
  { text: "A night of fun, laughter, and memories awaits. 🥂", keyword: "event" },
  { text: "🎶 Music, dance, and vibes. Get ready for an unforgettable night!", keyword: "event" },

  { text: "☕ Rise and grind!", keyword: "coffee" },
  { text: "Brew-tiful mornings start with coffee. 🌅", keyword: "coffee" },
  { text: "Sippin' on sunshine and caffeine. ☀️☕", keyword: "coffee" },
  { text: "Espresso yourself and seize the day! 💪", keyword: "coffee" },
  { text: "Coffee first, adulting second. 🙌", keyword: "coffee" },
  { text: "Morning brews and new dayviews. 🌞", keyword: "coffee" },
  { text: "Steamed, frothy, and ready to go! 🚀", keyword: "coffee" },
  { text: "Fueling up for the day's adventures. ☕️🛤️", keyword: "coffee" },
  { text: "Mornings are brew-tter with coffee. 😌", keyword: "coffee" },
  { text: "A cup of ambition to kickstart the day. 🌟", keyword: "coffee" },

  { text: "Monday: 🌅 New week, new goals, fresh start. Let's crush it! #MondayMotivation", keyword: "day" },
  { text: "Tuesday: ✌️ Tackling Tuesday with twice the energy and enthusiasm! #TwosDay", keyword: "day" },
  { text: "Wednesday: 🐪 Over the hump and sliding into the second half of the week. #WednesdayWisdom", keyword: "day" },
  { text: "Thursday: 🌟 One step closer to the weekend! Keeping the vibes high. #ThankfulThursday", keyword: "day" },
  { text: "Friday: 🎉 Fri-YAY vibes activated! Ready to wrap up the week with flair. #FridayFeeling", keyword: "day" },
  { text: "Saturday: 🎶 Weekend mode on! Time for relaxation and rejuvenation. #SaturdayShenanigans", keyword: "day" },
  { text: "Sunday: ☕ A day to refuel the soul and be grateful for each moment. #SundaySerenity", keyword: "day" },
  { text: "Monday Blues: 🔵 Even Mondays have their silver linings. Seeking mine! #BeatTheMondayBlues", keyword: "day" },
  { text: "Throwback Thursday: 🕰️ Taking a trip down memory lane and cherishing those golden moments. #TBT", keyword: "day" },
  { text: "Sunday Funday: 😄 Making the most of every Sunday second. Here's to laughter and memories! #SundayFunday", keyword: "day" },

  { text: "🌞 New week, new goals. Let's crush it!", keyword: "monday" },
  { text: "☕ May your coffee be strong and your Monday productive.", keyword: "monday" },
  { text: "🚀 Taking on Monday like it's the launchpad to success.", keyword: "monday" },
  { text: "😴 'Mondaze': When the weekend feels like a dream and Monday too real.", keyword: "monday" },
  { text: "🌱 Monday: A fresh start, a new chapter.", keyword: "monday" },
  { text: "💪 Embracing the Monday grind. Progress in the making!", keyword: "monday" },
  { text: "🎉 Turning Monday blues into Monday moves!", keyword: "monday" },
  { text: "📅 New Monday. New vibes. New opportunities.", keyword: "monday" },
  { text: "🤓 Mentally still on Sunday brunch, but let's do this, Monday!", keyword: "monday" },
  { text: "🌀 Rolling into the week like… #MondayMomentum", keyword: "monday" },

  { text: "Music = Life 🎵❤️", keyword: "music" },
  { text: "Lost in the rhythm of the melody. 🎧💭", keyword: "music" },
  { text: "Good vibes only when the beat drops! 🎶✨", keyword: "music" },
  { text: "When words fail, music speaks. 🎙️🎼", keyword: "music" },
  { text: "Tune in, world out. 🌍🎧", keyword: "music" },
  { text: "Feeling the beat in every heartbeat. ❤️🥁", keyword: "music" },
  { text: "Life's better with a soundtrack. 🎵🌈", keyword: "music" },
  { text: "Spinning stories, one track at a time. 📀📖", keyword: "music" },
  { text: "Volume up, worries down! 🎚️😌", keyword: "music" },
  { text: "Ears in heaven with this tune! 🎶👂", keyword: "music" },

  { text: "Dance is the hidden language of the soul. 💃🎶", keyword: "dance" },
  { text: "Shake it till you make it! 🕺💫", keyword: "dance" },
  { text: "Move to the beat of your dreams. 🎵👣", keyword: "dance" },
  { text: "Twirling into a world of wonder. 💃🌍", keyword: "dance" },
  { text: "Dancing is like dreaming with your feet. 🩰🌙", keyword: "dance" },
  { text: "Step, twist, leap, and repeat! 🎶🔄", keyword: "dance" },
  { text: "Music on, world off, dance floor conquered! 🎵🌌", keyword: "dance" },
  { text: "Groove, move, and prove that rhythm's in you. 🕺🎵", keyword: "dance" },
  { text: "Life's a dance, enjoy every step. 💃🌟", keyword: "dance" },
  { text: "Feet on the ground, but head in the clouds. Dancing away! 🩰☁️", keyword: "dance" },

  { text: "Every brushstroke tells a story. 🎨", keyword: "art" },
  { text: "Crafting dreams and colors into reality. ✨🖌️", keyword: "art" },
  { text: "Art is the journey of a free soul. 🕊️🎨", keyword: "art" },
  { text: "In every color, I see life. In every shadow, a story. 🌈", keyword: "art" },
  { text: "Art doesn't have to make sense, just feelings. 💭", keyword: "art" },
  { text: "Lost and found between the canvas and me. 🖼️❤️", keyword: "art" },
  { text: "Crafting my universe, one stroke at a time. 🌌", keyword: "art" },
  { text: "Breathe in inspiration and create wonders. 🍃🎨", keyword: "art" },
  { text: "Dripping in colors and dreams. 💧🎨", keyword: "art" },
  { text: "Art is not what you see, but what you make others see. 👀✨", keyword: "art" },

  { text: "Diving deep into a world between pages. 📖✨", keyword: "book" },
  { text: "Books: A unique portal to different universes. 🚀📚", keyword: "book" },
  { text: "So many books, so little time. ⏳❤️", keyword: "book" },
  { text: "Losing myself in tales and typography. 📚🌌", keyword: "book" },
  { text: "Between the pages of a book is a lovely place to be. 📖❤️", keyword: "book" },
  { text: "Drink tea, read books, be happy. ☕📖", keyword: "book" },
  { text: "Every chapter brings a new adventure. 🌍📚", keyword: "book" },
  { text: "Bookish and proud! 🤓📚", keyword: "book" },
  { text: "Books are dreams you can hold in your hands. ✨", keyword: "book" },
  { text: "Reading: A vacation for the mind. 🏖️📖", keyword: "book" },

  { text: "Dream big, sparkle more, shine bright. ✨💫", keyword: "inspiration" },
  { text: "Your vibe attracts your tribe. 🌟", keyword: "inspiration" },
  { text: "Be the energy you want to attract. 💡❤️", keyword: "inspiration" },
  { text: "Grow through what you go through. 🌱🌍", keyword: "inspiration" },
  { text: "Stars can't shine without darkness. 🌟🌚", keyword: "inspiration" },
  { text: "Trust the timing of your life. ⏳🌼", keyword: "inspiration" },
  { text: "The sun will rise, and we will try again. ☀️🔄", keyword: "inspiration" },
  { text: "Positive mind. Positive vibes. Positive life. 🌈✌️", keyword: "inspiration" },
  { text: "Believe in yourself and magic will happen. 🪄✨", keyword: "inspiration" },
  { text: "Fall seven times, stand up eight. 💪🔝", keyword: "inspiration" },

  { text: "ost in the reel magic. 🎥✨", keyword: "movie" },
  { text: "Film nights, where memories and scenes intertwine. 🍿🎬", keyword: "movie" },
  { text: "Every frame, a new emotion. 🎞️❤️", keyword: "movie" },
  { text: "Lights, camera, feels! 🎥💭", keyword: "movie" },
  { text: "Just another scene in the movie called 'Life'. 🌍🎬", keyword: "movie" },
  { text: "Reel stories, real emotions. 🎥🖤", keyword: "movie" },
  { text: "Life's better in widescreen. 🎞️🌆", keyword: "movie" },
  { text: "A binge-watcher's paradise. 📺🌌", keyword: "movie" },
  { text: "Hollywood dreams and silver screen scenes. 🌟🎥", keyword: "movie" },
  { text: "Making memories, one episode at a time. 🎬📅", keyword: "movie" },

  { text: "Why is this so relatable? 😂", keyword: "memes" },
  { text: "The struggle is real. 💯", keyword: "memes" },
  { text: "Meme game strong! 💪🔥", keyword: "memes" },
  { text: "Tag someone who gets it! 😂👇", keyword: "memes" },
  { text: "It's funny because it's true. 🤣", keyword: "memes" },
  { text: "If this isn't me… 🤷‍♀️", keyword: "memes" },
  { text: "Level of relatability: 1000% 💥", keyword: "memes" },
  { text: "Internet, you've done it again. 🤣", keyword: "memes" },
  { text: "Monday vibes in a meme. 🤦‍♂️", keyword: "memes" },
  { text: "Hit like if you've been there! 😂👍", keyword: "memes" },

  { text: "Where the magic happens! ✨🎨", keyword: "creativity" },
  { text: "Creating a world out of imagination and a dash of color. 🌈", keyword: "creativity" },
  { text: "Think outside the box. Or better yet, get rid of the box. 📦❌", keyword: "creativity" },
  { text: "Crafted with passion, presented with pride. 💖🖌️", keyword: "creativity" },
  { text: "Artistic soul with a wild heart. 🌟🍃", keyword: "creativity" },
  { text: "Every creation is a journey. Destination: Imagination. 🚀💭", keyword: "creativity" },
  { text: "Craftiness is happiness. 😊✂️", keyword: "creativity" },
  { text: "When in doubt, create something beautiful. 🎨❤️", keyword: "creativity" },
  { text: "Colors speak louder than words. 🌈🗣️", keyword: "creativity" },
  { text: "Creativity is contagious. Pass it on! 🎨🔄", keyword: "creativity" },

  { text: "Tech it out! 🖥️🚀", keyword: "technology" },
  { text: "The future is now. 🚀📱", keyword: "technology" },
  { text: "Wired for success. 🔌🎧", keyword: "technology" },
  { text: "Living in a tech-savvy world. 🌍💡", keyword: "technology" },
  { text: "Making the virtual, reality. 🕶️🔥", keyword: "technology" },
  { text: "Bytes and bots. 🤖💽", keyword: "technology" },
  { text: "Innovation today for a better tomorrow. 🚀🌟", keyword: "technology" },
  { text: "Smart tech, smarter solutions. 🧠📲", keyword: "technology" },
  { text: "From pixels to perfection. 🎨🖥️", keyword: "technology" },
  { text: "Bridging the gap between dreams and technology. 🌉💡", keyword: "technology" },
  { text: "Connecting the world, one click at a time 🌐💻✨",keyword: "technology" },
  { text: "Innovation is the future, and the future is now 🚀📱⚡",keyword: "technology" },
  { text: "Code, create, and conquer 💻🖱️💡",keyword: "technology" },
  { text: "Technology is the magic we create ✨🤖🌟",keyword: "technology" },
  { text: "Transforming ideas into reality, one algorithm at a time 💡🔗📈",keyword: "technology" },
  { text: "From wires to wireless, we've come a long way 🔌📡🌐",keyword: "technology" },
  { text: "Powered by caffeine and Wi-Fi ☕💻📶",keyword: "technology" },
  { text: "The best way to predict the future is to invent it 🚀💡🔧",keyword: "technology" },
  { text: "Let's innovate, inspire, and impact 🌍💻⚙️",keyword: "technology" },
  { text: "Tech is not just a tool; it's a lifestyle 💻📱✨",keyword: "technology" },
  { text: "Revolutionizing the world, one pixel at a time 🖥️🔍🌍",keyword: "technology" },
  { text: "Innovation never sleeps, and neither do we 🌙💡🖥️",keyword: "technology" },
  { text: "In a world of 0s and 1s, I choose infinite possibilities 💻",keyword: "technology" },

  { text: "Education is the most powerful weapon we can use to change the world. 📚🌍", keyword: "education" },
  { text: "Learn as if you will live forever. 🧠✨", keyword: "education" },
  { text: "The future belongs to the educated. 🎓🚀", keyword: "education" },
  { text: "From lessons to blessings. 📖❤️", keyword: "education" },
  { text: "Ignite the spark of knowledge. 🔥📚", keyword: "education" },
  { text: "The more you learn, the more you earn. 💡💰", keyword: "education" },
  { text: "Knowledge is power. 🧠💪", keyword: "education" },
  { text: "Dream. Learn. Do. Repeat. 💭📚🚀🔄", keyword: "education" },
  { text: "Education is not preparation for life",keyword: "education" },

  { text: "In business, vision is more important than sight. 🚀👓",keyword: "business" },
  { text: "Success usually comes to those too busy to be looking for it. 🏢💼",keyword: "business" },
  { text: "Empower. Innovate. Achieve. 🚀🔥",keyword: "business" },
  { text: "Business in the front, passion in the back. 💼❤️",keyword: "business" },
  { text: "Where strategy meets success. 📈🏆",keyword: "business" },
  { text: "Transforming visions into ventures. 🌍💡",keyword: "business" },
  { text: "Dress like the CEO you want to be. 👔🌟",keyword: "business" },
  { text: "Business as usual is never usual. 💼🔄",keyword: "business" },
  { text: "Redefining the business scape. 🏢🌍",keyword: "business" },
  { text: "Nurturing the seed of the next big idea. 💡🌱",keyword: "business" },
  { text: "Ideas: the blueprint of innovation. 🧠✨",keyword: "business" },
  { text: "One idea can change the business landscape. 🌍🚀",keyword: "business" },
  { text: "Brainstorms today, blue skies tomorrow. 🧠⛈️🌤️",keyword: "business" },
  { text: "Where imagination meets business. 💭💼",keyword: "business" },
  { text: "Turning dream bubbles into business realities. 💭🔮",keyword: "business" },
  { text: "In the world of ideas, everything is possible. 💡🌈",keyword: "business" },
  { text: "Dive deep into the ocean of possibilities. 🌊🧠",keyword: "business" },
  { text: "Ideate. Validate. Celebrate. 🎉💡",keyword: "business" },
  { text: "Business starts with a 'what if?' 💭🚀",keyword: "business" },

  { text: "Crafting content, curating connections. 📝🔗",keyword: "content" },
  { text: "In the digital realm, creativity is king. 🌐👑",keyword: "content" },
  { text: "From brainstorm to blog, the journey of a content creator. 💭🚀",keyword: "content" },
  { text: "Pixels, posts, and pure passion. 🖌️❤️",keyword: "content" },
  { text: "Storytelling in the age of screens. 📱📖",keyword: "content" },
  { text: "Ideas in ink, visions on video. 🖊️🎥",keyword: "content" },
  { text: "Crafted with care, created to captivate. 🎨🔍",keyword: "content" },
  { text: "Content isn't just words, it's an experience. 📝✨",keyword: "content" },
  { text: "Every piece tells a part of my story. 📜💬",keyword: "content" },
  { text: "Create. Captivate. Celebrate. 🎉🖌️",keyword: "content" },

  { text: "Blogging: My window to the world. 🌍💻",keyword: "blogging" },
  { text: "Putting pen to page, one post at a time. 🖊️📜",keyword: "blogging" },
  { text: "Journey through journals, adventure in articles. 📖🔍",keyword: "blogging" },
  { text: "From heartfelt to how-to: my blogging voyage. ❤️🔧",keyword: "blogging" },
  { text: "In the realm of words, every blogger is a king. 👑📝",keyword: "blogging" },
  { text: "Turn pages, touch lives. 📖❤️",keyword: "blogging" },
  { text: "From my desk to your device, with love. 💻❤️",keyword: "blogging" },
  { text: "Words that weave wonders. 📜✨",keyword: "blogging" },
  { text: "Blog vibes, best vibes. 💻🎉",keyword: "blogging" },
  { text: "A blogger's tale: where passion meets prose. 💭🖊️",keyword: "blogging" },

  { text: "Friends make the good times better and the hard times easier 👫❤️✨",keyword: "friends" },
  { text: "Partners in crime since day one 🕶️🚔💥",keyword: "friends" },
  { text: "Life's too short to not laugh with your besties 😂💃🕺",keyword: "friends" },
  { text: "A true friend is a treasure 🏆🤝✨",keyword: "friends" },
  { text: "Good friends = Great memories 📸🎉💞",keyword: "friends" },
  { text: "With friends like these, who needs a filter? 🌟📷💃",keyword: "friends" },
  { text: "Together, we're unstoppable 🌈🤩🔥",keyword: "friends" },
  { text: "Messy hair, crazy adventures, and unforgettable moments 🤪🍕📚",keyword: "friends" },
  { text: "The squad that slays together, stays together 💅🔥👑",keyword: "friends" },
  { text: "Some friendships are timeless ⏳❤️🌟",keyword: "friends" },
  { text: "Friendship isn't a big thing, it's a million little things 🌻💬💖",keyword: "friends" },
  { text: "Chasing sunsets and dreams with my faves 🌅✨💭",keyword: "friends" },
  { text: "Good vibes, great friends, and endless laughter 🎶🥂💃",keyword: "friends" },
  { text: "Friends who laugh together, grow together 🌱😂❤️",keyword: "friends" },
  { text: "Best friends are the family we choose 💕🏡👭",keyword: "friends" },

  { text: "Inner peace is the real wealth 🧘‍♀️🌿✨",keyword: "peace" },
  { text: "Serenity starts within 🌸☮️🌙",keyword: "peace" },
  { text: "Peace isn't a place; it's a state of mind 🌊🕊️💭",keyword: "peace" },
  { text: "Calm heart, clear mind, peaceful soul 🌼🧘‍♂️☀️",keyword: "peace" },
  { text: "Chasing sunsets and finding peace 🌅☁️✨",keyword: "peace" },
  { text: "Choose peace over chaos every day 🌿💖☮️",keyword: "peace" },
  { text: "Where there is peace, there is power 🕊️⚡💫",keyword: "peace" },  
  { text: "Let the waves wash away your worries 🌊🌞🕊️",keyword: "peace" },
  { text: "Find your calm in the storm 🌪️🌈🧘‍♀️",keyword: "peace" },
  { text: "A peaceful heart leads to a peaceful life 🌸☀️💭",keyword: "peace" },

  { text: "Bloom where you are planted 🌸🌿✨",keyword: "flower" },
  { text: "Stop and smell the roses 🌹☀️💖",keyword: "flower" },
  { text: "Like wildflowers, we must grow in all places 🌼🌾🍃",keyword: "flower" },
  { text: "Happiness blooms from within 🌻😊✨",keyword: "flower" },
  { text: "Petal power in full bloom 🌷💪🌟",keyword: "flower" },
  { text: "Every flower is a soul blossoming in nature 🌺🌳☀️",keyword: "flower" },
  { text: "Let your dreams bloom 🌸💭🌿",keyword: "flower" },
  { text: "Be a sunflower: stand tall and find the light 🌻🌞💛",keyword: "flower" },
  { text: "You belong among the wildflowers 🌼🍃🌸",keyword: "flower" },
  { text: "Life is better with flowers and sunshine 🌹🌤️💖",keyword: "flower" },

  { text: "Rooted in the earth, reaching for the sky 🌳🌤️✨",keyword: "tree" },
  { text: "Let your dreams grow as tall as the trees 🌲💭🌟",keyword: "tree" },
  { text: "Standing tall, weathering it all 🌴🌧️☀️",keyword: "tree" },
  { text: "Life's better under the shade of a tree 🍃🌳💚",keyword: "tree" },
  { text: "Deep roots are not reached by the frost 🌲❄️✨",keyword: "tree" },
  { text: "Like a tree, stay grounded yet rise high 🌳🍃☀️",keyword: "tree" },
  { text: "The best view comes after the hardest climb 🌲⛰️🌞",keyword: "tree" },
  { text: "In every walk with nature, we receive more than we seek 🌳🌺🌿",keyword: "tree" },
  { text: "Find peace in the forest's embrace 🌲🌸🕊️",keyword: "tree" },
  { text: "Trees teach us patience and strength 🌳💪🍃",keyword: "tree" },
  { text: "Nature's poetry is written in trees 🌴📖🌿",keyword: "tree" },
  { text: "Underneath the branches, life feels simpler 🌳✨🌍",keyword: "tree" },
  { text: "Plant kindness and let it grow 🌱💚🌲",keyword: "tree" },
  { text: "Lost in the woods, but found in the trees 🌲🌿✨",keyword: "tree" },
  { text: "Like leaves on a tree, we're all connected 🍃🌳🌟",keyword: "tree" },

  { text: "Go with the flow 🌊🍃✨",keyword: "river" },
  { text: "A river cuts through rock not by power, but by persistence 🌊🪨💪",keyword: "river" },
  { text: "Life is like a river—keep flowing 🌿🌀☀️",keyword: "river" },
  { text: "Take me where the river meets the sky 🌊🌤️🌈",keyword: "river" },
  { text: "Peaceful waters, endless dreams 🌊✨💭",keyword: "river" },
  { text: "Flow like a river, unstoppable and free 🌊🍃🌟",keyword: "river" },
  { text: "Rivers whisper the secrets of the earth 🌏🌊💬",keyword: "river" },
  { text: "Find me where the river sings 🌊🎶🌳",keyword: "river" },
  { text: "Life flows better by the riverbank 🌿🌊☀️",keyword: "river" },
  { text: "Every river has a story to tell 🌊📖✨",keyword: "river" },
  { text: "Wandering where the river takes me 🌊🌿🚶",keyword: "river" },
  { text: "Calm rivers run deep 🌊🍃💙",keyword: "river" },
  { text: "Let the river wash away all your worries 🌊💭🕊️",keyword: "river" },
  { text: "A walk by the river heals the soul 🌊🌳✨",keyword: "river" },
  { text: "Flowing towards new horizons 🌅🌊🌏",keyword: "river" },

  { text: "Rise and shine with the morning sun 🌅✨☀️",keyword: "sunrise" },
  { text: "Every sunrise is an invitation to a brighter day 🌞🌸💫",keyword: "sunrise" },
  { text: "Painted skies and a heart full of hope 🌅💖🌈",keyword: "sunrise" },
  { text: "Catching the first light of the day 🌄☀️🌿",keyword: "sunrise" },
  { text: "A sunrise is nature's way of smiling at us 🌞😊✨",keyword: "sunrise" },
  { text: "New day, new beginnings 🌅🌿💛",keyword: "sunrise" },
  { text: "Sunrises are proof that no matter what happens, life goes on 🌞🌄💫",keyword: "sunrise" },
  { text: "Chasing dreams as the sun rises 🌅✨🌏",keyword: "sunrise" },
  { text: "Morning magic in every ray of light 🌞☀️🌸",keyword: "sunrise" },
  { text: "The calm before the chaos 🌅🕊️✨",keyword: "sunrise" },
  { text: "Golden hues and peaceful views 🌄✨🍃",keyword: "sunrise" },
  { text: "Grateful for another day and another sunrise 🌞🙏🌸",keyword: "sunrise" },
  { text: "Whispering secrets to the dawn 🌅💭✨",keyword: "sunrise" },
  { text: "Where the sun meets the horizon, dreams begin 🌄🌈✨",keyword: "sunrise" },
  { text: "A sunrise a day keeps the gloom away 🌞✨😊",keyword: "sunrise" },

  { text: "Sunsets are proof that endings can be beautiful too 🌅✨💖",keyword: "sunset" },
  { text: "Chasing sunsets and collecting golden moments 🌇🌿✨",keyword: "sunset" },
  { text: "The sky paints a masterpiece every evening 🌅🎨🌈",keyword: "sunset" },
  { text: "Sunkissed and sunset blessed 🌞🌄💛",keyword: "sunset" },
  { text: "Peaceful vibes, golden skies 🌇🍃✨",keyword: "sunset" },
  { text: "Watching the sun say goodbye for the day 🌅🌴🌙",keyword: "sunset" },
  { text: "Every sunset is an opportunity to reset 🌄🧘‍♀️✨",keyword: "sunset" },
  { text: "End the day with a splash of color 🌅🎨🌸",keyword: "sunset" },
  { text: "Golden hour hits different 🌇💛✨",keyword: "sunset" },
  { text: "Dancing with the colors of the sunset 🌅💃🌈",keyword: "sunset" },
  { text: "The sun sets, but the memories last forever 🌇📸💖",keyword: "sunset" },
  { text: "Meet me where the sky touches the sea 🌅🌊💕",keyword: "sunset" },
  { text: "Cotton candy skies and endless goodbyes 🌅🍭✨",keyword: "sunset" },
  { text: "Sunset state of mind 🌇🌸🧘‍♀️",keyword: "sunset" },
  { text: "Let's follow the sun, even when it sets 🌄🌞✨",keyword: "sunset" },

  { text: "Family: where life begins and love never ends ❤️🏡✨",keyword: "family" },
  { text: "Home is wherever my family is 🏠💕🌟",keyword: "family" },
  { text: "Together is our favorite place to be 👨‍👩‍👧‍👦💖🌈",keyword: "family" },
  { text: "Family is the heart of every moment ❤️📸🌿",keyword: "family" },
  { text: "Blood makes us related, but love makes us family 💕✨👨‍👩‍👧",keyword: "family" },
  { text: "Built on love, laughter, and endless memories ❤️😂📖",keyword: "family" },
  { text: "Grateful for the ones who make my heart full 💖🙏🌟",keyword: "family" },
  { text: "Family: the roots of my being 🌳💕☀️",keyword: "family" },
  { text: "Love grows best in a home filled with family 🏡💖🌸",keyword: "family" },
  { text: "They are my people, my tribe, my everything ❤️🌏✨",keyword: "family" },
  { text: "Small moments, big memories 🏡📸💕",keyword: "family" },
  { text: "Family is a little bit of crazy, a little bit of loud, and a whole lot of love 😂❤️🌈",keyword: "family" },
  { text: "My family is my greatest blessing 💖",keyword: "family" },
  { text: "Happiness is homemade ❤️🍲🏡",keyword: "family" },
  { text: "We may not have it all together, but together we have it all 💕👨‍👩‍👧‍👦✨",keyword: "family" },

  { text: "Life is a beautiful journey, enjoy the ride 🚗🌍💫",keyword: "life" },
  { text: "Collecting moments, not things 📸💭✨",keyword: "life" },
  { text: "Chasing dreams and catching memories 💭🌟💖",keyword: "life" },
  { text: "Life isn't perfect, but it's beautiful 🌻💫🌸",keyword: "life" },
  { text: "Live life to the fullest, and let go of what you can't control 🌞🌿💖",keyword: "life" },
  { text: "Sometimes, the greatest adventure is simply a conversation 🌍🗣️✨",keyword: "life" },
  { text: "Make today amazing, tomorrow is not promised 🌞💫🌈",keyword: "life" },
  { text: "Life is short, make every day count ⏳💥💛",keyword: "life" },
  { text: "Take the risk or lose the chance 🎯✨💪",keyword: "life" },
  { text: "Breathe in positivity, breathe out negativity 🌿💨💛",keyword: "life" },
  { text: "Embrace the journey, trust the process 🚀🌟💫",keyword: "life" },
  { text: "Living my best life, one day at a time 🌟💃✨",keyword: "life" },
  { text: "Be a voice, not an echo 🌈💭🎤",keyword: "life" },
  { text: "Life's too short to wait for the perfect moment 🌻⏳💫",keyword: "life" },
  { text: "Create your own sunshine and shine bright 🌞✨🌈",keyword: "life" },

  { text: "Live simply, love deeply, laugh often 💖😂🌿",keyword: "lifestyle" },
  { text: "Good vibes and cozy times 🛋️☕✨",keyword: "lifestyle" },
  { text: "Life is what happens when you're busy making plans 🌿✨💭",keyword: "lifestyle" },
  { text: "Chasing dreams, sipping coffee, and enjoying the journey 🌟☕🚀",keyword: "lifestyle" },
  { text: "Simplicity is the ultimate sophistication 🌿✨💫",keyword: "lifestyle" },
  { text: "Creating a life I love, one day at a time 🌻🌞💖",keyword: "lifestyle" },
  { text: "Work hard, stay humble, and enjoy the little things 💼🌿💫",keyword: "lifestyle" },
  { text: "Surround yourself with those who bring out the best in you 💖🌟👯‍♀️",keyword: "lifestyle" },
  { text: "Living my best life, no filter needed 🌟✨📸",keyword: "lifestyle" },
  { text: "Self-love is the best lifestyle 💖🌸🧘‍♀️",keyword: "lifestyle" },
  { text: "Find beauty in the simple moments 🌸🌿🍃",keyword: "lifestyle" },
  { text: "A little bit of sunshine, a lot of good vibes 🌞🌈✨",keyword: "lifestyle" },
  { text: "Taking life one step at a time, with gratitude 🙏👣✨",keyword: "lifestyle" },
  { text: "Life's a journey, enjoy the ride 🚗🌍💖",keyword: "lifestyle" },
  { text: "Balance, peace, and good vibes only ✌️🌿💫",keyword: "lifestyle" },

  { text: "Nostalgia and giggles, that's what childhood is made of 🧸✨😂",keyword: "childhood" },
  { text: "Childhood memories are the best kind of treasures 💎👶🎈",keyword: "childhood" },
  { text: "Throwing it back to simpler times and endless playtime 🏃‍♀️🎠💫",keyword: "childhood" },
  { text: "Running wild, laughing loud, and loving life 🏃‍♂️😂💖",keyword: "childhood" },
  { text: "Catch me in my childhood dreams 🌟👶🎠",keyword: "childhood" },
  { text: "Collecting memories, one childhood moment at a time 🧸📸🌈",keyword: "childhood" },
  { text: "Playtime never really ends when you keep the childlike wonder alive 🌟🧸🚲",keyword: "childhood" },
  { text: "All I need is a playground and my imagination 🏰🎨🧸",keyword: "childhood" },
  { text: "Remembering when life was just about sweets and cartoons 🍬📺🎈",keyword: "childhood" },
  { text: "Sugar, spice, and everything nice—that's what childhood is made of 🍭🎀👧",keyword: "childhood" },
  { text: "The best childhood memories are the ones filled with laughter and love 😂❤️🌟",keyword: "childhood" },
  { text: "Let's be kids again, even if just for a moment 🏰🎠✨",keyword: "childhood" },
  { text: "In a world full of grown-ups, be a child at heart 🌈💖🧸",keyword: "childhood" },
  { text: "The days were long, and the fun never ended 🛹🎮🎉",keyword: "childhood" },
  { text: "Childhood: where every day is a new adventure 🏞️👦🎈",keyword: "childhood" },

  { text: "Life's too short to not have fun 😜🎉✨",keyword: "fun" },
  { text: "Good vibes and great times only 🌟🎶💃",keyword: "fun" },
  { text: "Make every day an adventure 🚀🎢🌈",keyword: "fun" },
  { text: "Fun times and sunny vibes only ☀️🎈💫",keyword: "fun" },
  { text: "Leave a little sparkle wherever you go ✨💃🌟",keyword: "fun" },
  { text: "Living for the moments that make me laugh the hardest 😂🎉🎊",keyword: "fun" },
  { text: "Doing what makes my soul happy 🕺🎶💖",keyword: "fun" },
  { text: "Fun is my middle name 🎉😎💥",keyword: "fun" },
  { text: "When in doubt, dance it out 💃🕺🎶",keyword: "fun" },
  { text: "Let the good times roll 🎲🎉🌟",keyword: "fun" },
  { text: "Fun is not a luxury, it's a necessity 🎈😜🌟",keyword: "fun" },
  { text: "Here for the moments that make life a little more exciting 🚀🎢💥",keyword: "fun" },
  { text: "The best memories are made when we're having fun 💫🎊🎉",keyword: "fun" },
  { text: "Laugh until your belly hurts, dance until your feet ache 😂💃✨",keyword: "fun" },
  { text: "Chasing fun and catching memories 📸🎉🎈",keyword: "fun" },

  { text: "I'm not arguing, I'm just explaining why I'm right 😜🤷‍♀️💬",keyword: "humour" },
  { text: "Laughter is the best therapy, and I'm a professional 😂💊💥",keyword: "humour" },
  { text: "If you can't laugh at yourself, I'll be happy to do it for you 😏🎉🤣",keyword: "humour" },
  { text: "My sense of humor is like a Wi-Fi signal: strong but sometimes spotty 📶😂💥",keyword: "humour" },
  { text: "I'm here to avoid friends on Facebook and make memories in real life 🤳😂😎",keyword: "humour" },
  { text: "Sarcasm: because beating people with sticks is illegal 🙃🦵✨",keyword: "humour" },
  { text: "I'm not lazy, I'm on energy-saving mode 😴💡💤",keyword: "humour" },
  { text: "Too cool for school… but still show up anyway 😎🎒📚",keyword: "humour" },
  { text: "I'm on a seafood diet: I see food and I eat it 🦞🍔😂",keyword: "humour" },
  { text: "My mood depends on how good my Wi-Fi is 📶😂📱",keyword: "humour" },
  { text: "Life is short, so smile while you still have teeth 😁💀",keyword: "humour" },
  { text: "Don't take life too seriously; nobody gets out alive anyway 💀😂",keyword: "humour" },
  { text: "I'm not weird, I'm just limited edition 🤪✨🎉",keyword: "humour" },
  { text: "I'm like a cloud. When I disappear, it's a beautiful day 🌥️☀️😂",keyword: "humour" },
  { text: "My imagination is so good, I could be a Netflix original series 🎬😂✨",keyword: "humour" },

  { text: "Celebrating tradition, embracing change 🌍💫🎉",keyword: "culture" },
  { text: "Culture is the soul of a nation 🌏💖🎨",keyword: "culture" },
  { text: "Where heritage meets modernity 🏛️✨🌿",keyword: "culture" },
  { text: "Rooted in tradition, growing with the times 🌱💫🎶",keyword: "culture" },
  { text: "Every culture tells a story 📖🌍✨",keyword: "culture" },
  { text: "In every culture, there's a beauty that shines through ✨🌏💖",keyword: "culture" },
  { text: "Exploring the world, one culture at a time 🌍🛫🎉",keyword: "culture" },
  { text: "Traditions are the ties that bind us together 🌸💫👐",keyword: "culture" },
  { text: "Living the rich tapestry of culture and diversity 🌍🎨✨",keyword: "culture" },
  { text: "Dancing to the rhythm of our heritage 💃🎶🌍",keyword: "culture" },
  { text: "The world is a colorful canvas of cultures 🎨🌍💖",keyword: "culture" },
  { text: "Every culture has a unique flavor 🍽️🌏🌶️",keyword: "culture" },
  { text: "In the blend of cultures, we find the true essence of life 🌍🍃💫",keyword: "culture" },
  { text: "Celebrating our differences, uniting in culture 🤝🌍✨",keyword: "culture" },
  { text: "Culture is the heart of humanity, beating through every tradition 💖🌍🎉",keyword: "culture" },

  { text: "Let the celebrations begin! 🎉🌟✨",keyword: "festival" },
  { text: "Festive vibes and joyful times 🎊🕯️💫",keyword: "festival" },
  { text: "Sparking joy and spreading love this festival season 🌟💖🎆",keyword: "festival" },
  { text: "The best time of the year is here! 🎉🎁✨",keyword: "festival" },
  { text: "Cheers to good food, great company, and endless festivities 🍽️🍷🎉",keyword: "festival" },
  { text: "Lights, colors, and laughter—this is what festivals are made of 🌟🎆🎊",keyword: "festival" },
  { text: "Embracing the joy and magic of the season 🎄✨🎉",keyword: "festival" },
  { text: "Dancing through the festival with a heart full of happiness 💃💖🎶",keyword: "festival" },
  { text: "Celebrating tradition and making new memories 🎉🎁✨",keyword: "festival" },
  { text: "When the heart is full, the festival shines brighter 🌟❤️🎆",keyword: "festival" },
  { text: "Festivals are all about creating memories with those who matter most 👫🎉🌟",keyword: "festival" },
  { text: "Sugar, spice, and everything nice—this festival has it all 🍬✨🎉",keyword: "festival" },
  { text: "A festival of lights, laughter, and love 💡🎊💖",keyword: "festival" },
  { text: "Let's fill the world with smiles and festive cheer 🌍😊🎉",keyword: "festival" },
  { text: "The festival is not just a celebration; it's a feeling 💖🎉✨",keyword: "festival" },

  { text: "Here for the fun, laughter, and good vibes 🎉✨🥳",keyword: "celebration" },
  { text: "Celebrating life, love, and everything in between 🥂🎉💖",keyword: "celebration" },
  { text: "When in doubt, celebrate everything 🎊💃✨",keyword: "celebration" },
  { text: "Life is a celebration—let's make every moment count 🕺💫🎉",keyword: "celebration" },
  { text: "Good times and great company make the best celebrations 🥳👯‍♀️✨",keyword: "celebration" },
  { text: "Cheers to another year of memories and celebrations 🥂🎉💫",keyword: "celebration" },
  { text: "Celebrating every small victory, because every win counts 🎊🥳🎉",keyword: "celebration" },
  { text: "Let's raise a toast to happiness and togetherness 🥂🎉❤️",keyword: "celebration" },
  { text: "This is what dreams and celebrations are made of ✨🥳🎊",keyword: "celebration" },
  { text: "Celebrating the moments that make life extraordinary 🎉💫🌟",keyword: "celebration" },
  { text: "Surround yourself with those who make every moment a celebration 🥳💖🎉",keyword: "celebration" },
  { text: "Here's to laughter, love, and unforgettable celebrations 🎶🎊❤️",keyword: "celebration" },
  { text: "Celebrating the good times, big or small 🥳✨🎉",keyword: "celebration" },
  { text: "Life's too short not to celebrate every little thing 🎉💃🌟",keyword: "celebration" },
  { text: "Pop the confetti, it's time to celebrate! 🎉🎈💖",keyword: "celebration" },

  { text: "The mountains are calling, and I must go 🏞️⛰️🌟",keyword: "mountain" },
  { text: "Climbing mountains and chasing dreams 🌄💭✨",keyword: "mountain" },
  { text: "The higher you climb, the better the view 🌄👀💙",keyword: "mountain" },
  { text: "Nature's beauty is at its peak ⛰️💚🌿",keyword: "mountain" },
  { text: "Take only pictures, leave only footprints 🏞️👣📸",keyword: "mountain" },
  { text: "Find your peace in the mountains 🌲⛰️💖",keyword: "mountain" },
  { text: "Adventure awaits on top of the world 🌏⛰️💫",keyword: "mountain" },
  { text: "Mountains are not obstacles, they are opportunities 🌄💪✨",keyword: "mountain" },
  { text: "Breathe in the mountain air and let it refresh your soul 🌲⛰️💨",keyword: "mountain" },
  { text: "Where the earth meets the sky 🌌⛰️🌟",keyword: "mountain" },
  { text: "Hike more, worry less 🏞️💚✨",keyword: "mountain" },
  { text: "The mountain teaches us to rise above 🌄💪🧘‍♀️",keyword: "mountain" },
  { text: "At the top, the world looks a little different 🏔️🌍✨",keyword: "mountain" },
  { text: "There's no Wi-Fi in the mountains, but you'll find a better connection 🌲📶💖",keyword: "mountain" },
  { text: "Living for the mountain moments 🏞️💖🏔️",keyword: "mountain" },

  { text: "Sky above, earth below, peace within 🌌🌍💫",keyword: "sky" },
  { text: "Chasing sunsets and counting stars 🌅✨🌟",keyword: "sky" },
  { text: "The sky is not the limit; it's just the beginning 🌈🚀✨",keyword: "sky" },
  { text: "When the sky paints a masterpiece, I stop and stare 🌅🎨✨",keyword: "sky" },
  { text: "Let the sky be your canvas 🌤️🎨🖌️",keyword: "sky" },
  { text: "Sunshine and blue skies, life's good 🌞🌈✨",keyword: "sky" },
  { text: "Every sunset brings the promise of a new dawn 🌅🌞💫",keyword: "sky" },
  { text: "Embrace the clouds, chase the sun ☁️🌞🌟",keyword: "sky" },
  { text: "The sky speaks in a language that can only be understood by the heart 🌌💖✨",keyword: "sky" },
  { text: "Sometimes, the sky is all you need to feel free 🌅🌍💙",keyword: "sky" },
  { text: "Under the same sky, we all shine 🌍🌙✨",keyword: "sky" },
  { text: "Lost in the beauty of the sky 💭🌌🌟",keyword: "sky" },
  { text: "Sky full of stars, heart full of dreams 🌟💭✨",keyword: "sky" },
  { text: "Dancing with the clouds, floating with the stars ☁️🌟💫",keyword: "sky" },
  { text: "Wander often, wonder always, look up at the sky 🌌✨👀",keyword: "sky" },

  { text: "Calm waters and peaceful vibes 🌊💙✨",keyword: "lake" },
  { text: "Life is better at the lake 🌅🏞️💦",keyword: "lake" },
  { text: "Just like the lake, let your soul be still 🌊🕊️💫",keyword: "lake" },
  { text: "The lake is my happy place 🌊🌞💖",keyword: "lake" },
  { text: "Where the water meets the sky 🌅🌊💙",keyword: "lake" },
  { text: "Chasing reflections and peaceful moments by the lake 🌅✨🏞️",keyword: "lake" },
  { text: "The lake calls, and I must go 🏞️🌊💖",keyword: "lake" },
  { text: "Nature's mirror, reflecting my peace 🌊✨🌿",keyword: "lake" },
  { text: "Floating through life with a lake breeze 🌊🍃🌞",keyword: "lake" },
  { text: "Serenity found by the water 🌊🕊️💙",keyword: "lake" },
  { text: "Like the calm waters, I find peace in stillness 🌊💭✨",keyword: "lake" },
  { text: "Good vibes and lake-side views 🌅🌊✨",keyword: "lake" },
  { text: "Tales are told in ripples on the water 🌊📖💫",keyword: "lake" },
  { text: "Take me to the lake, where the world slows down 🌊🏞️✨",keyword: "lake" },
  { text: "A day at the lake keeps the worries away 🌊💭💙",keyword: "lake" },

  { text: "Nature's playground, where every path leads to peace 🌳🌞💚",keyword: "park" },
  { text: "Fresh air, green grass, and endless adventures 🌳🛹🍃",keyword: "park" },
  { text: "Taking a break from the hustle to soak in the beauty of the park 🌿💚🌞",keyword: "park" },
  { text: "Parks are where magic and nature meet ✨🌳🦋",keyword: "park" },
  { text: "Every corner of the park whispers a new adventure 🌳💫🚶‍♀️",keyword: "park" },
  { text: "Let's wander where the Wi-Fi is weak and the trees are strong 🌳🍃📵",keyword: "park" },
  { text: "Taking time to smell the flowers and enjoy the sunshine 🌸🌞🌿",keyword: "park" },
  { text: "The park is my happy place 🌳💚🌼",keyword: "park" },
  { text: "Where the grass is greener and the air is sweeter 🌳🍃💖",keyword: "park" },
  { text: "A little walk in the park is all you need to reset 🌿🚶‍♂️🌞",keyword: "park" },
  { text: "Nature walks and park days are my kind of therapy 🌳💚🦋",keyword: "park" },
  { text: "The world is full of beautiful parks and peaceful moments 🌿✨🍃",keyword: "park" },
  { text: "Leave the city noise behind and find your peace in the park 🍃🌳💫",keyword: "park" },
  { text: "There's no better place to recharge than the park 🌿💚🌟",keyword: "park" },
  { text: "Exploring the park, one step at a time 🚶‍♀️🍃🌳",keyword: "park" },

  { text: "Flying high and embracing the freedom 🕊️💫🌤️",keyword: "bird" },
  { text: "Where the sky meets the wings of freedom 🦅☁️💙",keyword: "bird" },
  { text: "Birds are proof that freedom is beautiful 🕊️🌿✨",keyword: "bird" },
  { text: "Let your dreams soar as high as the birds 🦅💭🌟",keyword: "bird" },
  { text: "Just like birds, let's spread our wings and fly 🌤️🕊️✨",keyword: "bird" },
  { text: "Singing with the birds and dancing with the wind 🎶🕊️🍃",keyword: "bird" },
  { text: "The sky is the limit when you're as free as a bird 🦅🌤️",keyword: "bird" },
  { text: "Catching flights, not feelings ✈️🕊️✨",keyword: "bird" },
  { text: "Birds are the poetry of the sky 🕊️📜🌤️",keyword: "bird" },
  { text: "Chasing the winds and soaring high 🦅💨☁️",keyword: "bird" },
  { text: "Birds don't ask for permission to fly, and neither should you 🕊️🌟",keyword: "bird" },
  { text: "Every bird's flight reminds us of the beauty of freedom 🦅💫🌤️",keyword: "bird" },
  { text: "Fly like a bird, live like an adventure 🦅🌍💫",keyword: "bird" },
  { text: "Wings in the sky, dreams in my heart 🕊️💖🌟",keyword: "bird" },
  { text: "Birds remind us that sometimes, you just have to let go and soar 🦅🍃",keyword: "bird" },

  { text: "Let the rain wash away all the worries ☔💧✨",keyword: "rain" },
  { text: "Dancing in the rain, feeling alive 🌧️💃🌈",keyword: "rain" },
  { text: "The rain makes everything feel fresh and new ☔🌱💫",keyword: "rain" },
  { text: "Some people feel the rain, others just get wet 🌧️🌈💭",keyword: "rain" },
  { text: "Raindrops are like little kisses from the sky 💋☔💙",keyword: "rain" },
  { text: "The best thing about the rain is that it makes everything sparkle 🌧️✨💖",keyword: "rain" },
  { text: "Let's get lost in the sound of the rain 🌧️🎶💭",keyword: "rain" },
  { text: "A rainy day is the perfect excuse to stay cozy ☔🛋️☕",keyword: "rain" },
  { text: "When it rains, it pours... but I'm dancing through it 🌧️💃🌈",keyword: "rain" },
  { text: "Rainy days bring out the magic in the world 🌧️✨💫",keyword: "rain" },
  { text: "The sky is crying, but I'm smiling in the rain 🌧️😊💖",keyword: "rain" },
  { text: "Some find beauty in the sunshine, I find it in the rain 🌦️🌈💙",keyword: "rain" },
  { text: "Let the rain remind you that everything will be okay ☔💖✨",keyword: "rain" },
  { text: "Rain or shine, I'll always find beauty in the day 🌧️🌞💫",keyword: "rain" },
  { text: "Cloudy skies, but my heart is full of sunshine 🌧️💛🌤️",keyword: "rain" },

  { text: "A garden is a friend you can visit anytime 🌸🌿💚",keyword: "garden" },
  { text: "Growing dreams, one flower at a time 🌷✨🌱",keyword: "garden" },
  { text: "Bloom where you are planted 🌻💛🌿",keyword: "garden" },
  { text: "The garden is my happy place 🌸🌿😊",keyword: "garden" },
  { text: "In a world full of roses, be a wildflower 🌸🌾🌻",keyword: "garden" },
  { text: "Nature's artwork is always on display in the garden 🎨🌱💖",keyword: "garden" },
  { text: "Planting seeds of joy in my garden 🌱🌸💖",keyword: "garden" },
  { text: "Surrounded by beauty, one petal at a time 🌷🌿✨",keyword: "garden" },
  { text: "Let your garden grow as beautiful as your heart 🌻💖🌱",keyword: "garden" },
  { text: "The earth laughs in flowers 🌸😊🌿",keyword: "garden" },
  { text: "Sowing seeds of happiness in my garden 🌱💫🌼",keyword: "garden" },
  { text: "A little dirt never hurt, especially when it grows beauty 🌱💚🌸",keyword: "garden" },
  { text: "Every flower is a soul blossoming in nature 🌸🌿💚",keyword: "garden" },
  { text: "Lost in the beauty of my garden 🌻🌷🌿",keyword: "garden" },
  { text: "Gardening: where patience meets beauty 🌱🌸⏳",keyword: "garden" }

];
 

async function seedCaptions() {
  try {
    // Connect to MongoDB
    await mongoose.connect(mongoUrl, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log("Connected to MongoDB");

    // Insert captions with validation for uniqueness
    await Caption.insertMany(captions, { ordered: false });
    console.log("Captions seeded successfully");
  } catch (err) {
    if (err.code === 11000) {
      console.error("Duplicate entries found, skipped duplicates.");
    } else {
      console.error("Error seeding captions:", err);
    }
  } finally {
    mongoose.connection.close();
  }
}

seedCaptions();





